stages:
  - compile

  
compile_arduino_project:
  stage: compile
  image: ubuntu:20.04
  script:
    - apt-get update && apt-get install -y curl unzip python3-pip
    - pip install pyserial
    - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
    - arduino-cli core update-index 
      --additional-urls "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
    - arduino-cli core install esp32:esp32 
      --additional-urls "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"  
    - arduino-cli compile -b "esp32:esp32:esp32wroverkit" 
      --additional-urls "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json" /builds/team-project-h/2022/sh19/sh19-main/SensorESP32/SensorESP32.ino
